require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.4'

target 'Benji' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  target 'BenjiTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Benji-tvOS' do
  # Pods for Benji-tvOS

  target 'Benji-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
